# Generated by Django 2.0.4 on 2018-05-08 03:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('padmex', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreProd', models.CharField(max_length=200)),
                ('descripcionProd', models.CharField(max_length=2000)),
                ('precio', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='pedidos',
            name='cliente',
        ),
        migrations.AddField(
            model_name='cliente',
            name='correo',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(default=' ', max_length=20),
        ),
        migrations.DeleteModel(
            name='Pedidos',
        ),
        migrations.AddField(
            model_name='pedido',
            name='cliente_FK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='padmex.Cliente'),
        ),
        migrations.AddField(
            model_name='detalle',
            name='pedido_FK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='padmex.Pedido'),
        ),
        migrations.AddField(
            model_name='detalle',
            name='producto_FK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='padmex.Producto'),
        ),
    ]
