# Generated by Django 2.0.4 on 2018-05-08 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padmex', '0002_auto_20180507_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='passwd',
            field=models.CharField(max_length=20),
        ),
    ]
