# Generated by Django 2.0.4 on 2018-05-09 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('padmex', '0004_cita'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='status',
        ),
    ]
