# Generated by Django 2.0.4 on 2018-05-13 23:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('padmex', '0006_cita_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='contenido',
            field=models.TextField(default=' '),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='cliente_FK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
