# Generated by Django 2.0.4 on 2018-05-13 23:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('padmex', '0007_auto_20180513_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='cliente_FK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
