# Generated by Django 2.0.4 on 2018-05-14 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padmex', '0009_auto_20180514_0428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='correo',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='cita',
            name='telefono',
            field=models.CharField(default='', max_length=30),
        ),
    ]
