# Generated by Django 2.0.4 on 2018-05-14 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padmex', '0011_cita_asunto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.CharField(default='', max_length=20),
        ),
    ]
