# Generated by Django 2.0.4 on 2018-05-14 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('padmex', '0012_producto_categoria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cita',
            old_name='telefono',
            new_name='teléfono',
        ),
    ]
