# Generated by Django 2.0.4 on 2018-05-14 22:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('padmex', '0014_auto_20180514_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='fechaCita',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
