# Generated by Django 2.0.4 on 2018-05-14 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('padmex', '0015_cita_fechacita'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cita',
            old_name='fechaCita',
            new_name='fecha_cita',
        ),
    ]
