# Generated by Django 2.0.4 on 2018-05-09 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padmex', '0005_remove_cita_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='status',
            field=models.CharField(default='Por atender', max_length=20),
        ),
    ]
