# Generated by Django 2.0.4 on 2018-05-14 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padmex', '0008_auto_20180513_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='correo',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='cita',
            name='telefono',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
